//==============================================================================
// Hierarchical dofile generated by Conformal LEC
// Version: 20.10-p100 (01-May-2020) (64 bit executable)
//------------------------------------------------------------------------------
// The command 'set module property' sets the instance context for the current
// root module. It is intended only for hierarchical comparison, and should
// not be modified by the user.
//==============================================================================

set system mode setup
// Comparing module 'PC_DW01_add_1'
set root module PC_DW01_add_1 -Golden
set root module PC_DW01_add_1 -Revised
set module property -instance /PC_U0/add_x_1 -Golden
set module property -instance /PC_U0/add_x_1 -Revised
report black box -NOHidden
set system mode lec
analyze setup -verbose;                      analyze multiplier -cdp_info;                      analyze datapath -merge -share -effort medium -verbose;
add compared points -all
compare
analyze abort -compare
save hier_compare result
set system mode setup
add black box PC_DW01_add_1 -module -hier -Golden
add black box PC_DW01_add_1 -module -hier -Revised
// Comparing module 'IF_ID_DW01_add_0'
set root module IF_ID_DW01_add_0 -Golden
set root module IF_ID_DW01_add_0 -Revised
set module property -instance /IF_ID_U0/add_x_1 -Golden
set module property -instance /IF_ID_U0/add_x_1 -Revised
report black box -NOHidden
set system mode lec
analyze setup -verbose;                      analyze multiplier -cdp_info;                      analyze datapath -merge -share -effort medium -verbose;
add compared points -all
compare
analyze abort -compare
save hier_compare result
set system mode setup
add black box IF_ID_DW01_add_0 -module -hier -Golden
add black box IF_ID_DW01_add_0 -module -hier -Revised
// Comparing module 'imm_gen'
set root module imm_gen -Golden
set root module imm_gen -Revised
set module property -instance /imm_gen_U0 -Golden
set module property -instance /imm_gen_U0 -Revised
report black box -NOHidden
set system mode lec
analyze setup -verbose;                      analyze multiplier -cdp_info;                      analyze datapath -merge -share -effort medium -verbose;
add compared points -all
compare
analyze abort -compare
save hier_compare result
set system mode setup
add black box imm_gen -module -hier -Golden
add black box imm_gen -module -hier -Revised
// Comparing module 'ALU'
set root module ALU -Golden
set root module ALU -Revised
set module property -instance /ALU_U0 -Golden
set module property -instance /ALU_U0 -Revised
report black box -NOHidden
set system mode lec
analyze setup -verbose;                      analyze multiplier -cdp_info;                      analyze datapath -merge -share -effort medium -verbose;
add compared points -all
compare
analyze abort -compare
save hier_compare result
set system mode setup
add black box ALU -module -hier -Golden
add black box ALU -module -hier -Revised
// Comparing module 'stall_unit'
set root module stall_unit -Golden
set root module stall_unit -Revised
set module property -instance /stall_unit_U0 -Golden
set module property -instance /stall_unit_U0 -Revised
report black box -NOHidden
set system mode lec
analyze setup -verbose;                      analyze multiplier -cdp_info;                      analyze datapath -merge -share -effort medium -verbose;
add compared points -all
compare
analyze abort -compare
save hier_compare result
set system mode setup
add black box stall_unit -module -hier -Golden
add black box stall_unit -module -hier -Revised
// Comparing module 'nop_mux'
set root module nop_mux -Golden
set root module nop_mux -Revised
set module property -instance /nop_mux_U0 -Golden
set module property -instance /nop_mux_U0 -Revised
report black box -NOHidden
set system mode lec
analyze setup -verbose;                      analyze multiplier -cdp_info;                      analyze datapath -merge -share -effort medium -verbose;
add compared points -all
compare
analyze abort -compare
save hier_compare result
set system mode setup
add black box nop_mux -module -hier -Golden
add black box nop_mux -module -hier -Revised
// Comparing module 'forward_unit'
set root module forward_unit -Golden
set root module forward_unit -Revised
set module property -instance /forward_unit -Golden
set module property -instance /forward_unit -Revised
report black box -NOHidden
set system mode lec
analyze setup -verbose;                      analyze multiplier -cdp_info;                      analyze datapath -merge -share -effort medium -verbose;
add compared points -all
compare
analyze abort -compare
save hier_compare result
set system mode setup
add black box forward_unit -module -hier -Golden
add black box forward_unit -module -hier -Revised
// Comparing module 'top_riscv_core_DP_OP_21_122_7596_0'
set root module top_riscv_core_DP_OP_21_122_7596_0 -Golden
set root module top_riscv_core_DP_OP_21_122_7596_0 -Revised
set module property -instance /DP_OP_21_122_7596 -Golden
set module property -instance /DP_OP_21_122_7596 -Revised
report black box -NOHidden
set system mode lec
analyze setup -verbose;                      analyze multiplier -cdp_info;                      analyze datapath -merge -share -effort medium -verbose;
add compared points -all
compare
analyze abort -compare
save hier_compare result
set system mode setup
add black box top_riscv_core_DP_OP_21_122_7596_0 -module -hier -Golden
add black box top_riscv_core_DP_OP_21_122_7596_0 -module -hier -Revised
// Root modules
// Comparing module 'top_riscv_core'
set root module top_riscv_core -Golden
set root module top_riscv_core -Revised
set module property -instance / -Golden
set module property -instance / -Revised
report black box -NOHidden
set system mode lec
analyze setup -verbose;                      analyze multiplier -cdp_info;                      analyze datapath -merge -share -effort medium -verbose;
add compared points -all
compare
analyze abort -compare
save hier_compare result
set system mode setup
report hier_compare result
report hier_compare result -Non_equivalent
report hier_compare result -Abort
report hier_compare result -Uncompared
// _END_OF_LEC_HIERARCHICAL_DOFILE_
